export const siteConfig = {
  name: "AutoTrek Service Center",
  phoneDisplay: "(303) 328-3356",
  phoneHref: "tel:+13033283356",
  address: "8161 S Grant Way, Littleton, CO 80122",
  city: "Littleton",
  state: "CO",
  zip: "80122",
  hours: "Monday–Friday, 9:00 AM–5:00 PM",
  reviewUrl: "https://share.google/aglkPp86GrLFRfT7V",
  baseUrl: "https://autotrekservicecenter.com",
};
export type Service = { slug: string; name: string; short: string; };
export const services: Service[] = [
  { slug: "ac-service-repair-littleton-co", name: "AC Service & Repair", short: "Stay cool with diagnostics, recharge, and AC component repair." },
  { slug: "check-engine-light-diagnostics-littleton-co", name: "Check Engine Light Diagnostics", short: "Accurate diagnostics to identify issues and fix them right." },
  { slug: "ev-hybrid-repair-littleton-co", name: "EV & Hybrid Repair", short: "Specialized service for hybrid and EV systems." },
  { slug: "foreign-auto-repair-littleton-co", name: "Foreign Auto Repair", short: "Dealer-level care for import and European vehicles." },
  { slug: "minor-auto-service-littleton-co", name: "Minor Auto Service", short: "Quick, essential services to keep your car road-ready." },
  { slug: "oil-fluid-changes-littleton-co", name: "Oil & Fluid Changes", short: "Protect engine life with timely oil and fluid service." },
  { slug: "tires-wheels-littleton-co", name: "Tires & Wheels", short: "Tire rotation, balancing, and wheel service." },
  { slug: "4wd-light-inspection-littleton-co", name: "4WD Light Inspection", short: "Diagnose warning lights and drivetrain concerns." },
  { slug: "brake-repair-service-littleton-co", name: "Brake Repair & Service", short: "Safe, responsive braking with full-system inspection." },
  { slug: "dealer-service-alternative-littleton-co", name: "Dealer Service Alternative", short: "Premium maintenance without dealership hassle." },
  { slug: "factory-recommended-major-service-littleton-co", name: "Factory Recommended Major Service", short: "30k/60k/90k style services based on OEM guidance." },
  { slug: "pre-purchase-inspection-littleton-co", name: "Pre-Purchase Inspection", short: "Buy with confidence using our detailed inspection." },
  { slug: "steering-suspension-littleton-co", name: "Steering & Suspension", short: "Restore control, comfort, and handling precision." },
  { slug: "transmission-repair-littleton-co", name: "Transmission Repair", short: "From diagnostics to service and repair for transmissions." },
  { slug: "4x4-auto-repair-littleton-co", name: "4X4 Auto Repair", short: "Comprehensive 4x4 drivetrain and performance service." },
  { slug: "complete-auto-repair-littleton-co", name: "Complete Auto Repair", short: "Full-service diagnostics and repairs for daily reliability." },
  { slug: "domestic-auto-repair-littleton-co", name: "Domestic Auto Repair", short: "Trusted service for American makes and models." },
  { slug: "fleet-repair-service-littleton-co", name: "Fleet Repair & Service", short: "Keep business vehicles dependable and on schedule." },
  { slug: "maintenance-lights-littleton-co", name: "Maintenance Lights", short: "Warning light diagnosis with practical next steps." },
  { slug: "preventative-maintenance-littleton-co", name: "Preventative Maintenance", short: "Reduce major breakdowns with proactive care." },
  { slug: "timing-belt-repair-littleton-co", name: "Timing Belt Repair", short: "Avoid major engine damage with timely replacement." },
  { slug: "wheel-alignment-littleton-co", name: "Wheel Alignment", short: "Improve tire life and handling with precise alignment." },
];
export const areas = [
  { slug: "littleton-co", name: "Littleton, CO", title: "Trusted Auto Repair in Littleton, CO" },
  { slug: "highlands-ranch-co", name: "Highlands Ranch, CO", title: "Trusted Auto Repair Near Highlands Ranch, CO" },
  { slug: "englewood-co", name: "Englewood, CO", title: "Reliable Auto Repair Near Englewood, CO" },
  { slug: "lakewood-co", name: "Lakewood, CO", title: "Professional Auto Repair Near Lakewood, CO" },
  { slug: "centennial-co", name: "Centennial, CO", title: "Dependable Auto Repair Near Centennial, CO" },
];
